spring.application.name=hrms-recruitment-api
server.port=8082

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://ep-damp-dawn-axy8q1p2-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_g6sXeNcW7mtG

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.ignore-migration-patterns=*:ignored